__all__ = [
    "DEFAULT_IMAGE_HEIGHT",
    "DEFAULT_IMAGE_WIDTH",
    "DEFAULT_CAMERA_SOURCE",
    "MIN_OPENCV_CAMERA_PROPERTY",
    "MAX_OPENCV_CAMERA_PROPERTY",
    "DEFAULT_KERNEL_SIZE"
]

DEFAULT_IMAGE_HEIGHT = 240
DEFAULT_IMAGE_WIDTH = 320
DEFAULT_CAMERA_SOURCE = 0
MIN_OPENCV_CAMERA_PROPERTY = 0
MAX_OPENCV_CAMERA_PROPERTY = 18
DEFAULT_KERNEL_SIZE = (3, 3)
